(require 'lazy-set-key)
(require 'xcwen-misc)

(require 'init-evil)
(require 'init-jedi)
(require 'init-mode)
(require 'init-term)
(require 'init-yasnippet)
(require 'init-indent)
(require 'init-auto-complete)
(require 'init-key)
(require 'init-startup)
(require 'init-session)

(provide 'init)
