#!/bin/bash
cd `dirname $0 ` 
[ -d ./tags_dir ] || mkdir ./tags_dir
#
file_list=`find  ../ -name "[A-Za-z0-9_]*.php" ! -path "../.tags/*" `
#echo $file_list
obj_list=""
>./tags
for file_name in $file_list
{
	#echo $file_name
	opt_file_name=${file_name//\//-}
	obj_file="./tags_dir/"${opt_file_name:3:-3}"tags"
	if [ -f  $obj_file ]; then
		ret_str="`find   $file_name  -newer  $obj_file  2>/dev/null`" 
	else
		ret_str=$file_name
	fi	
	if [ "$ret_str" != "" ];then
		echo "complete:" $ret_str;
		phpctags  --sort=no  -f $obj_file   $ret_str  
	fi

	obj_list="$obj_list $obj_file"

}

cat $obj_list >> ./tags

#phpctags  --sort=no $file_list
./gen_el_tags.py 

echo "$file_list" > cscope.files
cscope -bkq -i cscope.files

